package com.opt.ssafy.optback.domain.challenge.exception;

public class ChallengeRecordNotFoundException extends RuntimeException {
    public ChallengeRecordNotFoundException(String message) {
        super(message);
    }
}
